# -*- coding: utf-8 -*-
"""Weather_Predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12-5n7abBVV6Lt_QZhCgOL09uS33If4k8

# **WEATHER PREDICTION**

**Load the data**
"""

import requests
import pandas as pd

# 1. Set up the API call for 14 years of Kolkata weather data
url = "https://archive-api.open-meteo.com/v1/archive"
params = {
    "latitude": 22.5726,
    "longitude": 88.3639,
    "start_date": "2010-01-01",
    "end_date": "2023-12-31",
    "daily": ["temperature_2m_max", "temperature_2m_min", "temperature_2m_mean", "precipitation_sum"],
    "timezone": "auto"
}

# 2. Fetch the data
print("Downloading 14 years of weather data... ⏳")
response = requests.get(url, params=params)
data = response.json()

# 3. Convert to a clean Pandas DataFrame
weather_data = pd.DataFrame(data['daily'])

# 4. Rename columns for easier access
weather_data.rename(columns={
    'time': 'Date',
    'temperature_2m_max': 'MaxTemp',
    'temperature_2m_min': 'MinTemp',
    'temperature_2m_mean': 'AvgTemp',
    'precipitation_sum': 'Rainfall'
}, inplace=True)

# 5. Format the dates and clean missing values
weather_data['Date'] = pd.to_datetime(weather_data['Date'])
weather_data.set_index('Date', inplace=True)
weather_data = weather_data.dropna()

print(f"✅ Success! Loaded {len(weather_data)} days of historical data.")
display(weather_data.head())

"""**Research Phase**"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error
import pandas as pd

# --- PART A: FEATURE ENGINEERING (Ensuring columns exist) ---
df = weather_data.copy()
df['MaxTemp_Yesterday'] = df['MaxTemp'].shift(1)
df['MaxTemp_2DaysAgo'] = df['MaxTemp'].shift(2)
df['MaxTemp_3DaysAgo'] = df['MaxTemp'].shift(3)
df['Rainfall_Yesterday'] = df['Rainfall'].shift(1)
df['Target_Tomorrow_MaxTemp'] = df['MaxTemp'].shift(-1)
df = df.dropna()

# --- PART B: THE SHOOTOUT ---
# 1. Define our Features (X) and Target (y)
X = df[['MaxTemp_Yesterday', 'MaxTemp_2DaysAgo', 'MaxTemp_3DaysAgo', 'Rainfall_Yesterday']]
y = df['Target_Tomorrow_MaxTemp']

# 2. Time-Series Split (80% Train, 20% Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# 3. Define the Competitors
models = {
    "Baseline (Linear Regression)": LinearRegression(),
    "Ensemble (Random Forest)": RandomForestRegressor(n_estimators=100, random_state=42),
    "Heavyweight (XGBoost)": XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42)
}

# 4. Run the Tournament
print("Starting the 14-Year Data Model Shootout...\n")
results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    mae = mean_absolute_error(y_test, predictions)
    results.append({"Model": name, "Error (°C)": mae})
    print(f" {name} finished testing.")

# 5. Display the final leaderboard
results_df = pd.DataFrame(results).sort_values(by="Error (°C)")

print("\n --- FINAL RESULTS (Lowest Error Wins) --- ")
display(results_df)

"""### Predicted vs. Actual Temperature for the Best Model (XGBoost)"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 7))
sns.scatterplot(x=y_test, y=predictions, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2) # Perfect prediction line
plt.title('XGBoost: Predicted vs. Actual Max Temperature (Test Set)')
plt.xlabel('Actual Max Temperature (°C)')
plt.ylabel('Predicted Max Temperature (°C)')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()